Game lobby screen grizzly
sopra-fs24-group-41/sopra-fs24-group-41-client pull request #62
Opened 2024-04-04 21:04 UTC by Grizzlytron

I implemented the basic functionality with the list of users and showing the game modes. The game modes can be selected and are highlighted whenever selected. Also added a start Game button which is only enabled whenever a gamemode is selected and the User is the lobby owner. 

Should be just a basic template which we can build up on.
The Quit button still needs to be added, but it can be worked with to start off.

Let me know what else I could add or if there's missing functionality.

2024-04-04 21:07 UTC, Grizzlytron commented
To do:
Add Quit Button
Selecting Gamemodes should be disabled for players that are not lobby masters

2024-04-05 09:14 UTC, na50r requested changes
For the time being, I mainly fixed up some CSS such that it looks like this:

![Uploading image.png…]()

It's not finite but atm it polished up what you've already implemented. I think we should probably discuss what we want to put in the center and what to the left or right or if we want to keep it like this. Great work.



I put all my changes explicitly in the reviews but if you wanna be lazy:

- `Lobby.tsx`
Replace: `{player.name}` with <div className="player name">{player.name}</div>

- `Lobby.scss`
Copy-paste this:
```css
@import "../theme";

/* The '&' is a shorthand for the containing element,
  so for example a '&.user-list' inside .game will compile to
  .game.user-list

  for more information visit https://sass-lang.com/guide
 */

.lobbypage {
  &.container {
    float: left;
    background: $background;
    padding: 1.5em;
    border-radius: $borderRadius;
    display: flex;
    flex-direction: column;
    align-items: center;
    box-shadow: $dropShadow;
    margin-left: 30px;
  }
  & p,
  h2 {
    margin: 0.5em 0;
  }
}

.gamemode {

  &:hover {transform: translateY(-2px);}
  &.container {
    text-align: start;
    margin: 0.5em 0;
    width: auto;
    padding: 12px;
    padding-left: 30px;
    padding-right: 30px;
    border-radius: $borderRadius;
    display: flex;
    flex-direction: column;
    align-items: center;
    background: lighten($background, 20);
    cursor: pointer;

    &.selected {
      background: lighten($background, 25);
      border: solid rgb(0, 0, 0)
    }
  }

 &.name {
  text-align: center;
  margin: auto;
  color: $accentDark;
  text-transform: uppercase;
}

&.description {
  color: $textColor;
  margin-top: 5px;
  text-align: center;
}

  &.list {
        list-style: none;
          padding-left: 0;
          text-align: center;
          max-height: 300px;
          overflow-y: auto;
          overflow-x: hidden;
  }

        

}

.player {
  &.container {
    padding-right: 50px;
    background: lighten($background, 20);
    padding: 4px;
    border-radius: $borderRadius;
    display: flex;
    flex-direction: row;
    align-items: start;
    width: 200px;
  }

  &.list {
        list-style: none;
          padding-left: 0;
          text-align: center;
          max-height: 400px;
          overflow-y: auto;
          overflow-x: hidden;
  }

  &.name{
    margin-top: 30px;
  }

  &.icon {
    position: relative;
    top: 10%;
    max-width: 80px;
    max-height: 80px;

    img {
      width: 75px;
      height: 75px;
      border-radius: 25%;
      border: 5px solid rgb(26, 26, 26)
    }
  }
}

.container-wrapper {
  position: relative;
  display: flex;
  justify-content: space-between;
}
```

2024-04-05 09:14 UTC, na50r commented on src/styles/views/Lobby.scss
> +    padding: 20px;
Replace with  `padding: 12px`
Add
```css
    padding-left: 30px;
    padding-right: 30px;
```

2024-04-05 09:14 UTC, na50r commented on src/styles/views/Lobby.scss
> +    align-items: center;
Add `flex-direction: column;`
This will make the desc go below the game mode name.

2024-04-05 09:14 UTC, na50r commented on src/styles/views/Lobby.scss
> +    color: $textColor;
Add
```css
  margin-top: 5px;
  text-align: center;
```

2024-04-05 09:14 UTC, na50r commented on src/styles/views/Lobby.scss
> +    text-align: center;
Add
```css
padding-left: 0;
max-height: 300px;
overflow-y: auto;
overflow-x: hidden;


```

2024-04-05 09:14 UTC, na50r commented on src/styles/views/Lobby.scss
> +    float: left;
Remove `float:left`
Change `padding: 20px` to `padding: 4px`
Change `flex-direction: column` to `flex-direction: row` (will display player names to the right of icon)

2024-04-05 09:14 UTC, na50r commented on src/styles/views/Lobby.scss
> +  &.list {
Add:
```css
  text-align: center;
  max-height: 400px;
  overflow-y: auto;
  overflow-x: hidden;

```

2024-04-05 09:14 UTC, na50r commented on src/styles/views/Lobby.scss
> +
Add:
```css
  &.name{
    margin-top: 30px;
  }
```
This will put the player name to the center (vertically)

2024-04-05 09:14 UTC, na50r commented on src/styles/views/Lobby.scss
> +    max-width: 150px;
Change `max-width: 150px` to `max-width: 80px`
Change `max-height: 150px` to `max-height: 80px`

This is still debatable but in a player overview, I don't think profile icons should take up too much space.

2024-04-05 09:14 UTC, na50r commented on src/components/views/Lobby.tsx
> +                            {player.name}
Put `player.name` in a `<div>`, i.e.:
Replace `{player.name}`
With
```css
<div className="player name">{player.name}</div>
```

2024-04-05 10:12 UTC, na50r commented
@Tmmn Requested some further changes and I did some CSS trickery to get this:
![image](https://github.com/sopra-fs24-group-41/sopra-fs24-group-41-client/assets/145561869/c93d6ab0-10ec-4f25-bd66-ca9c43953f45)


This one is not final either because it felt wrong to completely work on @Grizzlytron code when he was absent, so I just played around and got the basic idea there. What is still needed is to adjust the sizes of the Player list box and put the Game modes more to the center, or perhaps put the playerbox in the center and the game modes to the left.

Here the revised CSS
```css
@import "../theme";

/* The '&' is a shorthand for the containing element,
  so for example a '&.user-list' inside .game will compile to
  .game.user-list

  for more information visit https://sass-lang.com/guide
 */

.lobbypage {
  &.container {
    float: left;
    background: $background;
    padding: 1.5em;
    border-radius: $borderRadius;
    display: flex;
    flex-direction: column;
    align-items: center;
    box-shadow: $dropShadow;
    margin-left: 30px;
  }

  & p,
  h2 {
    margin: 0.5em 0;
  }

  &.game-and-players-container {
    display: flex;
    justify-content: space-between;
    width: 100%;
  }
}

.gamemode {



  &.container {
    &:hover {
    transform: translateY(-2px);
        }

    text-align: start;
    margin: 0.5em 0;
    width: auto;
    padding: 12px;
    padding-left: 30px;
    padding-right: 30px;
    border-radius: $borderRadius;
    display: flex;
    flex-direction: column;
    align-items: center;
    background: lighten($background, 20);
    cursor: pointer;

    &.selected {
      background: lighten($background, 25);
      border: solid rgb(0, 0, 0)
    }
  }

  &.name {
    text-align: center;
    margin: auto;
    color: $accentDark;
    text-transform: uppercase;
  }

  &.description {
    color: $textColor;
    margin-top: 5px;
    text-align: center;
  }

  &.list {
    list-style: none;
    padding-left: 0;
    text-align: center;
    max-height: 300px;
    overflow-y: auto;
    overflow-x: hidden;
  }
}

.player {
  &.container {
    padding-right: 50px;
    background: lighten($background, 20);
    padding: 4px;
    border-radius: $borderRadius;
    display: flex;
    flex-direction: row;
    align-items: start;
    width: 200px;
  }

  &.list {
    list-style: none;
    padding-left: 0;
    text-align: center;
    max-height: 400px;
    overflow-y: auto;
    overflow-x: hidden;
  }

  &.name {
    margin-top: 30px;
  }

  &.icon {
    position: relative;
    top: 10%;
    max-width: 80px;
    max-height: 80px;

    img {
      width: 75px;
      height: 75px;
      border-radius: 25%;
      border: 5px solid rgb(26, 26, 26)
    }
  }
}

.container-wrapper {
  position: relative;
  display: flex;
  justify-content: space-between;
}

.player-list-container {
  float: left;
  background: darken($background, 4);
  padding: 1.5em;
  border-radius: $borderRadius;
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-left: 30px;}
```

Here what you need to return in `Lobby.tsx`
```ts
return (
  <div className="container-wrapper">
    <BaseContainer>
      <div className="lobbypage container">
        <h2>Grealish Lobby</h2>
        <p>Select a Gamemode</p>
        <div className="lobbypage game-and-players-container">
          <div className="gamemode">{content}</div>
          <BaseContainer className="player-list-container">
            <div className="player-list">
              {usercontent}
            </div>
          </BaseContainer>
        </div>
      </div>
    </BaseContainer>
  </div>
);
```

2024-04-07 10:25 UTC, na50r approved these changes
Looks good to me.

2024-04-07 11:01 UTC, Tmmn approved these changes

2024-04-07 11:24 UTC, merged